#!/bin/bash
make -j
esptool.py --chip esp32 --port /dev/ttyUSB0 --baud 115200 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 40m --flash_size detect 0x1000 bootloader/bootloader.bin 0x10000 bluepad32.bin 0x8000 partition_table/partition-table.bin

screen /dev/ttyUSB0 115200
